apiVersion: v1
kind: Pod
metadata:
  name: with-affinity-anti-affinity
spec:
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 1
        preference:
          matchExpressions:
          - key: project
            operator: In
            values:
            - amazon
      - weight: 50
        preference:
          matchExpressions:
          - key: project
            operator: In
            values:
            - roboshop
  containers:
  - name: with-node-affinity
    image: registry.k8s.io/pause:2.0
