apiVersion: v1
kind: Pod
metadata:
  name: annotations
  labels:
    course: DevOps
    Trainer: "SivakumarReddy"
  annotations:
    com.roboshop.training.duration: "120 hours"
    jenkins.url: "https://jenkins.com/roboshop/catalogue#45"
spec:
  # list of containers
  containers:
  - name: hello-pod
    image: nginx
    ports:
    - containerPort: 80