apiVersion: v1
kind: Pod
metadata:
  name: config-pod
spec:
  # list of containers
  containers:
  - name: config-pod
    image: nginx
    #here with this line port will not be opened, just for information
    ports:
    - containerPort: 80
    env:
    - name: course
      valueFrom:
        configMapKeyRef:
          name: devops-config
          key: course
    - name: trainer
      valueFrom:
        configMapKeyRef:
          name: devops-config
          key: trainer